# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4646e8b30a9913c6a88be172ed38152a5e3c9db6b23e516df23bb3896743d770774258b8f237d0ee993b7a42873bcbfa0e865265e9cd40cd0cf22b89df666496

test:
  secret_key_base: 608b5ce1eab5bf9d5d93b98682de66de7d86e4d39df4fa69a71c46891ce7c36f6b03d1e5453106fbbaaf2fdee28e504ab1f38e641819c5444a1132241e8d6cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
